### PR TITLE
Delete sSignal.module.lua

### PR DESCRIPTION
**Pull request by Validark**
[We have this now](https://github.com/RoStrap/Events)
This would deep-copy tables passed to Fire()

### CODE REVIEW

**Comment by devSparkle** [comment]
@Validark I'll look into porting sSignal to the Events library.

**Comment by Validark** [comment]
It's already in there?

**Comment by devSparkle** [comment]
@Validark I'd like to map sSignal functions to the Events library.

**Comment by Validark** [comment]
I don't understand what that means

**Pull request closed without merging**
